name: Create PostgreSQL Table

on: [push]

env:
  POSTGRES_HOST: "postgresschema"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgresschema.postgres.database.azure.com"
  POSTGRES_USER: "schema01@postgresschema"
  POSTGRES_PASSWORD: "Schema@01"

jobs:
  create_table:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up PostgreSQL CLI
      uses: docker://postgres:12
      env:
        POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
        POSTGRES_PORT: ${{ env.POSTGRES_PORT }}
        POSTGRES_DB: ${{ env.POSTGRES_DB }}
        POSTGRES_USER: ${{ env.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
    
    - name: Create table
      run: |
        psql -h ${{ env.POSTGRES_HOST }} \
             -p ${{ env.POSTGRES_PORT }} \
             -U ${{ env.POSTGRES_USER }} \
             -c "CREATE TABLE users (id SERIAL PRIMARY KEY, username VARCHAR(255), email VARCHAR(255));" \
             ${{ env.POSTGRES_DB }}
